apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless-llm.backend.fullname" . }}
  labels:
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.config.api.port }}
      targetPort: http
