apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-llm.config.fullname" . }}
type: Opaque
stringData:
  config.yaml: |
    database:
      host: {{ include "paperless-llm.database.host" . | quote }}
      port: {{ include "paperless-llm.database.port" . }}
      username: {{ include "paperless-llm.database.username" . | quote }}
      password: {{ include "paperless-llm.database.password" . | quote }}
      database: {{ include "paperless-llm.database.name" . | quote }}

    redis:
      host: {{ include "paperless-llm.redis.host" . | quote }}
      port: {{ include "paperless-llm.redis.port" . }}
      username: {{ include "paperless-llm.redis.username" . | quote }}
      password: {{ include "paperless-llm.redis.password" . | quote }}
      db: {{ include "paperless-llm.redis.db" . }}
      ttlInSeconds: {{ .Values.config.redisCache.ttlInSeconds }}

    paperless:
      url: {{ .Values.config.paperless.url | quote }}
      token: {{ .Values.config.paperless.token | quote }}

    llm:
      url: {{ .Values.config.llm.url | quote }}

    workers:
      instanceId: {{ .Values.config.workers.instanceId | default "null" }}

    logging:
      level: {{ .Values.config.logging.level | quote }}
      pretty: {{ .Values.config.logging.pretty }}

    api:
      port: {{ .Values.config.api.port }}
      corsOrigins:
        {{- range .Values.config.api.corsOrigins }}
        - {{ . | quote }}
        {{- end }}

    auth:
      jwtSecret: {{ .Values.config.auth.jwtSecret | quote }}
      jwtExpiresIn: {{ .Values.config.auth.jwtExpiresIn | quote }}
