apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless-llm.server.fullname" . }}
  labels:
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: {{ .Values.server.config.api.port }}
      targetPort: http
