/**
 * Paperless-LLM API
 * REST API for the Paperless-LLM document processing system.   This API enables automated document processing workflows using Large Language Models (LLMs) to generate document metadata such as titles, tags, and summaries. It supports both automated and approval-based workflows with comprehensive job tracking, queue management, and step-level retry mechanisms.  ## Key Features - **Job Submission**: Submit batch processing jobs for multiple documents - **Workflow Management**: Track job progress through multi-step workflows - **Approval System**: Review and approve/reject LLM-generated suggestions - **Queue Monitoring**: Real-time visibility into processing queues - **Prompt Customization**: Customize LLM prompts for different processing steps - **Health Monitoring**: Monitor system and service health status - **Retry Mechanism**: Automatic retry with exponential backoff for failed steps  ## Architecture The system follows a clean architecture pattern with: - Domain-Driven Design principles - Step-based workflow orchestration - Transaction management for data consistency - RFC 7807 Problem Details for error responses 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Document } from '../models/Document.js';
import { DocumentAction } from '../models/DocumentAction.js';
import { JobState } from '../models/JobState.js';
import { WorkflowType } from '../models/WorkflowType.js';
import { HttpFile } from '../http/http.js';

export class JobResponse {
    'id': string;
    'fields'?: Array<JobResponseFieldsEnum>;
    'documentId': number;
    'jobType': WorkflowType;
    'status': JobState;
    /**
    * Error message if job failed
    */
    'errorMessage'?: string | null;
    'createdAt': Date;
    'updatedAt': Date;
    'completedAt'?: Date | null;
    'documentActions': Array<DocumentAction>;
    /**
    * Document metadata for the job\'s document
    */
    'document'?: Document | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<JobResponseFieldsEnum>",
            "format": ""
        },
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "number",
            "format": ""
        },
        {
            "name": "jobType",
            "baseName": "jobType",
            "type": "WorkflowType",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "JobState",
            "format": ""
        },
        {
            "name": "errorMessage",
            "baseName": "errorMessage",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "completedAt",
            "baseName": "completedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "documentActions",
            "baseName": "documentActions",
            "type": "Array<DocumentAction>",
            "format": ""
        },
        {
            "name": "document",
            "baseName": "document",
            "type": "Document",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JobResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum JobResponseFieldsEnum {
    title = 'title',
    tags = 'tags',
    correspondent = 'correspondent',
    document_type = 'document_type',
    created_date = 'created_date'
}

